import "@/styles/globals.css";

import { Suspense } from "react";
import { redirect } from "next/navigation";
import { Toaster } from "sonner";

import { GeistSans } from "geist/font/sans";
import { cookies } from "next/headers";
import NextTopLoader from "nextjs-toploader";
import { TRPCReactProvider } from "@/trpc/react";
import { getServerAuthSession } from "@/server/auth";

import Navbar from "../_components/Navbar";

export const metadata = {
  title: "INC UMS",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  if (!session?.user) return redirect("/");
  return (
    <html lang="en">
      <body className={`font-sans ${GeistSans.className}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <NextTopLoader showSpinner={false} />
          <Suspense>
            <Navbar />
          </Suspense>
          <main className="p-10">{children}</main>
          <Toaster richColors />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
